# Numpy

In [1]:
import numpy as np

## Jednorozmerné pole

In [2]:
p1 = np.array([1,3,5,7,9])
p1.__class__

numpy.ndarray

In [3]:
p1.shape

(5,)

In [10]:
p1[3]

np.int64(7)

## Dvojrozmerné pole

In [12]:
p2=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]    
])
p2.shape

(3, 4)

In [13]:
p2[1]

array([5, 6, 7, 8])

In [14]:
p2[1,3]

np.int64(8)

In [15]:
# slices
p2[0:2,2:]

array([[3, 4],
       [7, 8]])

## Priradenie float hodnoty do integer

In [16]:
p2[2,3]

np.int64(12)

In [20]:
p2[2,3]=17.64

In [21]:
p2[2,3]

np.int64(17)

In [22]:
p2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 17]])

## Priradenie stringu do integer

In [23]:
p2[2,3] = 'test'

ValueError: invalid literal for int() with base 10: 'test'

## Defaultné polia

### Pole núl

In [27]:
pole0 = np.zeros((5,6))
pole0

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
pole0.dtype

dtype('float64')

In [33]:
pole0[1,1] = 100
pole0

array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0., 100.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.]])

In [29]:
pole0int = np.zeros((5,6), dtype='int32')
pole0int

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [30]:
pole0int.dtype

dtype('int32')

In [32]:
pole0int[1,1] = 100
pole0int

array([[  0,   0,   0,   0,   0,   0],
       [  0, 100,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0]], dtype=int32)

### Pole jednotiek

In [34]:
pole1int = np.ones((6,5), dtype='int32')
pole1int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [35]:
pole1int.dtype

dtype('int32')

### Pole tuple-ov

In [38]:
poleTuples = np.zeros((3,4), dtype=('i4, f4, S10'))
poleTuples

array([[(0, 0., b''), (0, 0., b''), (0, 0., b''), (0, 0., b'')],
       [(0, 0., b''), (0, 0., b''), (0, 0., b''), (0, 0., b'')],
       [(0, 0., b''), (0, 0., b''), (0, 0., b''), (0, 0., b'')]],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [39]:
poleTuples.dtype.names= ('signed integer', 'float', 'string')

In [40]:
poleTuples

array([[(0, 0., b''), (0, 0., b''), (0, 0., b''), (0, 0., b'')],
       [(0, 0., b''), (0, 0., b''), (0, 0., b''), (0, 0., b'')],
       [(0, 0., b''), (0, 0., b''), (0, 0., b''), (0, 0., b'')]],
      dtype=[('signed integer', '<i4'), ('float', '<f4'), ('string', 'S10')])

In [41]:
?pass

Object `pass` not found.


## Výkonnosť

### Magická funkcia %timeit

In [62]:
def multiplyListByScalar (list, scalar):
    """
    každý element v liste prenásobí skalárom
    list: iterable zoznam
    scalar: číselná hodnota
    return: upravený list
    """
    for index,elem in enumerate(list):
        list[index] = scalar*elem
    return list

### Porovnanie np array a listu

In [55]:
bigArray = np.arange(1e7)
bigArray

array([0.000000e+00, 1.000000e+00, 2.000000e+00, ..., 9.999997e+06,
       9.999998e+06, 9.999999e+06])

In [56]:
bigList = bigArray.tolist()
bigList[:10]

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [57]:
print(f"{len(bigList):_}")

10_000_000


#### Výkonnosť listu

In [63]:
%timeit -n 10 multiplyListByScalar(bigList,1.3)

677 ms ± 8.69 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [65]:
%timeit -n 10 [1.3*elem for elem in bigList]

803 ms ± 29.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### Výkonnosť np array

In [67]:
%timeit -n 10 1.3*bigArray

33.9 ms ± 1.44 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [66]:
%timeit -n 10 multiplyListByScalar(bigArray,1.3)

2.2 s ± 157 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
A naopak: prenásobenie skalárom celý list (ako pri np array) nefunguje

In [68]:
%timeit -n 10 1.3*bigList

TypeError: can't multiply sequence by non-int of type 'float'

## Výkonnosť numba

In [69]:
import numpy as np

In [97]:
bigA = np.random.randint(1,20,1_000_000).reshape((1_000, 1_000))
bigA.shape

(1000, 1000)

In [98]:
bigA[:10,:10]

array([[ 1, 13,  8, 19, 17,  4, 12, 17, 10,  4],
       [ 1,  2, 10,  3,  2,  3, 17, 16, 15,  8],
       [10, 19, 15, 16,  5,  4,  8,  4, 12,  2],
       [17,  3, 13, 16, 11, 11,  3, 19, 13,  3],
       [19,  2, 17, 18,  4,  8,  7,  4, 14,  1],
       [ 3,  1,  6,  5, 10, 10,  7, 10,  4, 19],
       [ 1, 11,  2,  1,  6,  3,  1,  1,  5,  4],
       [16, 14, 10, 15,  7, 14, 17, 15, 16,  3],
       [ 9,  6, 12,  5, 14, 15, 15, 18, 10, 11],
       [ 8, 15, 18, 12,  8, 16, 15,  6,  7,  1]], dtype=int32)

In [99]:
def sumArr(arr):
    result =0.0
    M,N = arr.shape
    for i in range(M):
        for j in range(N):
            result += arr[i,j]
    return result

In [100]:
%%time

for _ in range(20):
    sumArr(bigA)

CPU times: total: 4.97 s
Wall time: 5.25 s


In [102]:
from numba import jit

In [103]:
@jit
def sumArr_JIT(arr):
    result =0.0
    M,N = arr.shape
    for i in range(M):
        for j in range(N):
            result += arr[i,j]
    return result

In [104]:
%%time

for _ in range(20):
    sumArr_JIT(bigA)

CPU times: total: 625 ms
Wall time: 1.08 s


asi 8krat rychlejsie

## Dalsie operacie s numpy

In [107]:
z = np.random.uniform(1,10,100).reshape((10,10))
z

array([[3.1578625 , 5.15025786, 9.92270086, 1.98475409, 8.76960967,
        5.09659939, 6.05150671, 3.06096507, 2.68557371, 6.00752694],
       [4.56200495, 7.68810602, 2.7070902 , 2.98819031, 5.79607903,
        3.83015079, 1.99553014, 3.232774  , 3.48691849, 1.22059771],
       [6.13697873, 2.34861084, 1.00272673, 2.69321853, 1.78450045,
        6.76894045, 5.35197648, 1.28991335, 5.17759408, 3.00100552],
       [5.15188691, 1.2333877 , 8.07699913, 9.49100484, 2.02026277,
        3.90099285, 8.69340973, 8.67337594, 7.79552484, 6.40796101],
       [4.02217976, 6.36366675, 6.05128972, 8.90024356, 2.49011864,
        4.92808129, 5.73267996, 3.42428381, 5.81746349, 8.05691012],
       [6.05410214, 4.02263148, 6.9813995 , 9.56083589, 1.87973927,
        5.98445356, 1.50637144, 5.13121926, 6.16464819, 1.56753781],
       [2.6726551 , 7.61146468, 9.60824624, 1.57042744, 4.45677587,
        5.18132249, 9.01365753, 6.97369563, 3.767902  , 2.68230041],
       [5.58960053, 6.66769474, 5.4442854

In [109]:
z+1

array([[ 4.1578625 ,  6.15025786, 10.92270086,  2.98475409,  9.76960967,
         6.09659939,  7.05150671,  4.06096507,  3.68557371,  7.00752694],
       [ 5.56200495,  8.68810602,  3.7070902 ,  3.98819031,  6.79607903,
         4.83015079,  2.99553014,  4.232774  ,  4.48691849,  2.22059771],
       [ 7.13697873,  3.34861084,  2.00272673,  3.69321853,  2.78450045,
         7.76894045,  6.35197648,  2.28991335,  6.17759408,  4.00100552],
       [ 6.15188691,  2.2333877 ,  9.07699913, 10.49100484,  3.02026277,
         4.90099285,  9.69340973,  9.67337594,  8.79552484,  7.40796101],
       [ 5.02217976,  7.36366675,  7.05128972,  9.90024356,  3.49011864,
         5.92808129,  6.73267996,  4.42428381,  6.81746349,  9.05691012],
       [ 7.05410214,  5.02263148,  7.9813995 , 10.56083589,  2.87973927,
         6.98445356,  2.50637144,  6.13121926,  7.16464819,  2.56753781],
       [ 3.6726551 ,  8.61146468, 10.60824624,  2.57042744,  5.45677587,
         6.18132249, 10.01365753,  7.97369563

In [110]:
z>5

array([[False,  True,  True, False,  True,  True,  True, False, False,
         True],
       [False,  True, False, False,  True, False, False, False, False,
        False],
       [ True, False, False, False, False,  True,  True, False,  True,
        False],
       [ True, False,  True,  True, False, False,  True,  True,  True,
         True],
       [False,  True,  True,  True, False, False,  True, False,  True,
         True],
       [ True, False,  True,  True, False,  True, False,  True,  True,
        False],
       [False,  True,  True, False, False,  True,  True,  True, False,
        False],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True],
       [ True, False, False,  True,  True,  True,  True,  True, False,
        False],
       [False,  True, False,  True,  True, False, False, False,  True,
         True]])

In [111]:
z%1

array([[0.1578625 , 0.15025786, 0.92270086, 0.98475409, 0.76960967,
        0.09659939, 0.05150671, 0.06096507, 0.68557371, 0.00752694],
       [0.56200495, 0.68810602, 0.7070902 , 0.98819031, 0.79607903,
        0.83015079, 0.99553014, 0.232774  , 0.48691849, 0.22059771],
       [0.13697873, 0.34861084, 0.00272673, 0.69321853, 0.78450045,
        0.76894045, 0.35197648, 0.28991335, 0.17759408, 0.00100552],
       [0.15188691, 0.2333877 , 0.07699913, 0.49100484, 0.02026277,
        0.90099285, 0.69340973, 0.67337594, 0.79552484, 0.40796101],
       [0.02217976, 0.36366675, 0.05128972, 0.90024356, 0.49011864,
        0.92808129, 0.73267996, 0.42428381, 0.81746349, 0.05691012],
       [0.05410214, 0.02263148, 0.9813995 , 0.56083589, 0.87973927,
        0.98445356, 0.50637144, 0.13121926, 0.16464819, 0.56753781],
       [0.6726551 , 0.61146468, 0.60824624, 0.57042744, 0.45677587,
        0.18132249, 0.01365753, 0.97369563, 0.767902  , 0.68230041],
       [0.58960053, 0.66769474, 0.4442854

In [112]:
np.floor(z)

array([[3., 5., 9., 1., 8., 5., 6., 3., 2., 6.],
       [4., 7., 2., 2., 5., 3., 1., 3., 3., 1.],
       [6., 2., 1., 2., 1., 6., 5., 1., 5., 3.],
       [5., 1., 8., 9., 2., 3., 8., 8., 7., 6.],
       [4., 6., 6., 8., 2., 4., 5., 3., 5., 8.],
       [6., 4., 6., 9., 1., 5., 1., 5., 6., 1.],
       [2., 7., 9., 1., 4., 5., 9., 6., 3., 2.],
       [5., 6., 5., 6., 9., 1., 9., 2., 5., 6.],
       [5., 1., 3., 5., 6., 5., 9., 6., 3., 1.],
       [4., 7., 2., 5., 6., 3., 4., 1., 6., 8.]])

In [113]:
data = np.random.randint(1,20,100).reshape((10,10))
data

array([[ 7, 16, 15,  6, 12,  6, 11,  1,  4,  3],
       [ 4, 11,  7,  1,  7, 16,  6,  9,  6,  2],
       [12, 18,  7, 19, 19, 12, 16,  8, 18, 17],
       [12,  6,  4, 13, 15, 16,  1,  2,  1,  8],
       [16,  7, 16,  7, 16, 18,  8, 11,  6,  4],
       [ 1, 16, 11, 10, 12,  3, 12, 15, 16, 10],
       [ 2,  6, 13,  2,  4,  5, 12, 10, 16,  6],
       [17, 11, 11,  7,  5,  4, 10, 19,  4,  5],
       [17, 15,  6,  5, 16, 10, 18, 10, 12,  8],
       [13,  3, 18, 12,  1, 16, 17,  2,  6, 10]], dtype=int32)

In [114]:
jeParne = data%2 == 0
jeParne

array([[False,  True, False,  True,  True,  True, False, False,  True,
        False],
       [ True, False, False, False, False,  True,  True, False,  True,
         True],
       [ True,  True, False, False, False,  True,  True,  True,  True,
        False],
       [ True,  True,  True, False, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True,  True,  True, False,  True,
         True],
       [False,  True, False,  True,  True, False,  True, False,  True,
         True],
       [ True,  True, False,  True,  True, False,  True,  True,  True,
         True],
       [False, False, False, False, False,  True,  True, False,  True,
        False],
       [False, False,  True, False,  True,  True,  True,  True,  True,
         True],
       [False, False,  True,  True, False,  True, False,  True,  True,
         True]])

In [116]:
lenParne = data[jeParne]
lenParne

array([16,  6, 12,  6,  4,  4, 16,  6,  6,  2, 12, 18, 12, 16,  8, 18, 12,
        6,  4, 16,  2,  8, 16, 16, 16, 18,  8,  6,  4, 16, 10, 12, 12, 16,
       10,  2,  6,  2,  4, 12, 10, 16,  6,  4, 10,  4,  6, 16, 10, 18, 10,
       12,  8, 18, 12, 16,  2,  6, 10], dtype=int32)

In [118]:
np.random.seed(1234)
arr = np.random.randint(1,25,12).reshape((3,4))
arr

array([[16, 20,  7, 22],
       [13, 21, 16, 18],
       [24, 10, 12, 13]], dtype=int32)

In [120]:
arr.sort(axis=0) # podla riadku
arr # je to destruktivne

array([[13, 10,  7, 13],
       [16, 20, 12, 18],
       [24, 21, 16, 22]], dtype=int32)

In [121]:
np.random.seed(1234)
arr = np.random.randint(1,25,12).reshape((3,4))
arr

array([[16, 20,  7, 22],
       [13, 21, 16, 18],
       [24, 10, 12, 13]], dtype=int32)

In [122]:
arr.sort(axis=1) # podla riadku
arr

array([[ 7, 16, 20, 22],
       [13, 16, 18, 21],
       [10, 12, 13, 24]], dtype=int32)