# Numpy

In [3]:
import numpy as np

## Jednorozmerné pole

In [5]:
p1 = np.array([1,3,5,7,9])
p1.__class__

numpy.ndarray

In [6]:
p1.shape

(5,)

In [10]:
p1[3]

np.int64(7)

## Dvojrozmerné pole

In [12]:
p2=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]    
])
p2.shape

(3, 4)

In [13]:
p2[1]

array([5, 6, 7, 8])

In [14]:
p2[1,3]

np.int64(8)

In [15]:
# slices
p2[0:2,2:]

array([[3, 4],
       [7, 8]])

## Priradenie float hodnoty do integer

In [16]:
p2[2,3]

np.int64(12)

In [20]:
p2[2,3]=17.64

In [21]:
p2[2,3]

np.int64(17)

In [22]:
p2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 17]])

## Priradenie stringu do integer

In [23]:
p2[2,3] = 'test'

ValueError: invalid literal for int() with base 10: 'test'

## Defaultné polia

### Pole núl

In [27]:
pole0 = np.zeros((5,6))
pole0

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
pole0.dtype

dtype('float64')

In [33]:
pole0[1,1] = 100
pole0

array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0., 100.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.]])

In [29]:
pole0int = np.zeros((5,6), dtype='int32')
pole0int

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [30]:
pole0int.dtype

dtype('int32')

In [32]:
pole0int[1,1] = 100
pole0int

array([[  0,   0,   0,   0,   0,   0],
       [  0, 100,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0]], dtype=int32)

### Pole jednotiek

In [34]:
pole1int = np.ones((6,5), dtype='int32')
pole1int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [35]:
pole1int.dtype

dtype('int32')

### Pole tuple-ov

In [38]:
poleTuples = np.zeros((3,4), dtype=('i4, f4, S10'))
poleTuples

array([[(0, 0., b''), (0, 0., b''), (0, 0., b''), (0, 0., b'')],
       [(0, 0., b''), (0, 0., b''), (0, 0., b''), (0, 0., b'')],
       [(0, 0., b''), (0, 0., b''), (0, 0., b''), (0, 0., b'')]],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [39]:
poleTuples.dtype.names= ('signed integer', 'float', 'string')

In [40]:
poleTuples

array([[(0, 0., b''), (0, 0., b''), (0, 0., b''), (0, 0., b'')],
       [(0, 0., b''), (0, 0., b''), (0, 0., b''), (0, 0., b'')],
       [(0, 0., b''), (0, 0., b''), (0, 0., b''), (0, 0., b'')]],
      dtype=[('signed integer', '<i4'), ('float', '<f4'), ('string', 'S10')])

In [41]:
?pass

Object `pass` not found.


## Výkonnosť

### Magická funkcia %timeit

In [62]:
def multiplyListByScalar (list, scalar):
    """
    každý element v liste prenásobí skalárom
    list: iterable zoznam
    scalar: číselná hodnota
    return: upravený list
    """
    for index,elem in enumerate(list):
        list[index] = scalar*elem
    return list

### Porovnanie np array a listu

In [55]:
bigArray = np.arange(1e7)
bigArray

array([0.000000e+00, 1.000000e+00, 2.000000e+00, ..., 9.999997e+06,
       9.999998e+06, 9.999999e+06])

In [56]:
bigList = bigArray.tolist()
bigList[:10]

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [57]:
print(f"{len(bigList):_}")

10_000_000


#### Výkonnosť listu

In [63]:
%timeit -n 10 multiplyListByScalar(bigList,1.3)

677 ms ± 8.69 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [65]:
%timeit -n 10 [1.3*elem for elem in bigList]

803 ms ± 29.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### Výkonnosť np array

In [67]:
%timeit -n 10 1.3*bigArray

33.9 ms ± 1.44 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [66]:
%timeit -n 10 multiplyListByScalar(bigArray,1.3)

2.2 s ± 157 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
A naopak: prenásobenie skalárom celý list (ako pri np array) nefunguje

In [68]:
%timeit -n 10 1.3*bigList

TypeError: can't multiply sequence by non-int of type 'float'

# DOKONCIT

## Výkonnosť numba

## ...