# Pandas

In [1]:
import numpy as np

In [2]:
import pandas as pd

## Pandas Series

### Vytvoriť random np array

In [3]:
np.random.seed(12345)
data_array = np.random.rand(7)
data_array

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452])

### Prekonvertovať random array do series a nastaviť indexy

In [4]:
data_series = pd.Series(data_array)
data_series # jednorozmerny, indexovany

0    0.929616
1    0.316376
2    0.183919
3    0.204560
4    0.567725
5    0.595545
6    0.964515
dtype: float64

In [5]:
data_series.index

RangeIndex(start=0, stop=7, step=1)

### Nastaviť v series ako index názvy dní

In [6]:
import calendar as cal

In [7]:
cal.day_name[:7]

['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

In [8]:
data_series.index = cal.day_name[:7]

In [9]:
data_series.index

Index(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
       'Sunday'],
      dtype='object')

In [10]:
data_series

Monday       0.929616
Tuesday      0.316376
Wednesday    0.183919
Thursday     0.204560
Friday       0.567725
Saturday     0.595545
Sunday       0.964515
dtype: float64

#### Pozicovanie elementu v series

In [11]:
data_series[5]

C:\Users\educa\AppData\Local\Temp\ipykernel_10796\2676657597.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data_series[5]


np.float64(0.5955447029792516)

In [12]:
data_series.iloc[5]

np.float64(0.5955447029792516)

In [13]:
data_series.loc['Saturday']

np.float64(0.5955447029792516)

### Kalendár cez series

In [14]:
cal_series = pd.Series(np.arange(1,13), index=cal.month_name[1:13])
cal_series

January       1
February      2
March         3
April         4
May           5
June          6
July          7
August        8
September     9
October      10
November     11
December     12
dtype: int64

In [15]:
cal_series.__class__

pandas.core.series.Series

In [16]:
cal_series['March': 'October': 2]

March        3
May          5
July         7
September    9
dtype: int64

## Pandas DataFrame

In [17]:
df = pd.DataFrame({'alfa': range(1,6), 'beta': range(6,11)})
df

alfa  beta
0     1     6
1     2     7
2     3     8
3     4     9
4     5    10

In [18]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [19]:
df.columns

Index(['alfa', 'beta'], dtype='object')

### Pozicovanie v dataframe

In [20]:
df.loc[3, 'alfa']

np.int64(4)

In [21]:
df['alfa']

0    1
1    2
2    3
3    4
4    5
Name: alfa, dtype: int64

In [22]:
df.alfa

0    1
1    2
2    3
3    4
4    5
Name: alfa, dtype: int64

### Pridanie / rename stĺpca

In [23]:
df[' mercedes benz '] = range(101, 106)

In [24]:
df

alfa  beta   mercedes benz 
0     1     6              101
1     2     7              102
2     3     8              103
3     4     9              104
4     5    10              105

In [25]:
df.rename(columns={' mercedes benz ': 'alfa romeo'})

alfa  beta  alfa romeo
0     1     6         101
1     2     7         102
2     3     8         103
3     4     9         104
4     5    10         105

In [26]:
df

alfa  beta   mercedes benz 
0     1     6              101
1     2     7              102
2     3     8              103
3     4     9              104
4     5    10              105

In [27]:
# inplace treba nastaviť
df.rename(columns={' mercedes benz ': 'alfa romeo'}, inplace=True)

In [28]:
df

alfa  beta  alfa romeo
0     1     6         101
1     2     7         102
2     3     8         103
3     4     9         104
4     5    10         105

In [29]:
df.rename(columns={'alfa romeo': 'alfa_romeo'}, inplace=True)

In [30]:
df

alfa  beta  alfa_romeo
0     1     6         101
1     2     7         102
2     3     8         103
3     4     9         104
4     5    10         105

### Iné

In [31]:
df.describe()

alfa       beta  alfa_romeo
count  5.000000   5.000000    5.000000
mean   3.000000   8.000000  103.000000
std    1.581139   1.581139    1.581139
min    1.000000   6.000000  101.000000
25%    2.000000   7.000000  102.000000
50%    3.000000   8.000000  103.000000
75%    4.000000   9.000000  104.000000
max    5.000000  10.000000  105.000000

In [32]:
df.median()

alfa            3.0
beta            8.0
alfa_romeo    103.0
dtype: float64

In [33]:
df.alfa_romeo.median()

np.float64(103.0)

In [34]:
df.index = cal.day_abbr[0: len(df)]
df

alfa  beta  alfa_romeo
Mon     1     6         101
Tue     2     7         102
Wed     3     8         103
Thu     4     9         104
Fri     5    10         105

In [35]:
df.drop(columns='alfa_romeo', inplace=True)

In [36]:
df

alfa  beta
Mon     1     6
Tue     2     7
Wed     3     8
Thu     4     9
Fri     5    10

# OBCE - s GPS súradnicami

In [37]:
filename = "C:/Users/educa/Documents/STUDY/GOPAS/labfiles/DATA/OBCE_GPS.csv"
filename

'C:/Users/educa/Documents/STUDY/GOPAS/labfiles/DATA/OBCE_GPS.csv'

In [38]:
data = pd.read_csv(filename, delimiter=',')
data.head()

Unnamed: 0        DOBEC         OBEC            OKRES     PSC      DPOSTA  \
0           0      Ábelová      Ábelová          Lučenec  985 13     Ábelová   
1           1       Abovce       Abovce  Rimavská Sobota  980 44  Lenartovce   
2           2      Abrahám      Abrahám          Galanta  925 45     Abrahám   
3           3  Abrahámovce  Abrahámovce         Bardejov  086 41   Raslavice   
4           4  Abrahámovce  Abrahámovce         Kežmarok  059 72       Vrbov   

        POSTA  KOD_OKR KRAJ        LAT        LNG  
0     Ábelová      606   BC  48.410817  19.431741  
1  Lenartovce      609   BC  48.318828  20.339351  
2     Abrahám      202   TA  48.250846  17.616963  
3   Raslavice      701   PV  49.161432  21.343484  
4       Vrbov      703   PV  49.044580  20.439083

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4210 entries, 0 to 4209
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  4210 non-null   int64  
 1   DOBEC       4210 non-null   object 
 2   OBEC        4210 non-null   object 
 3   OKRES       4210 non-null   object 
 4   PSC         4154 non-null   object 
 5   DPOSTA      4154 non-null   object 
 6   POSTA       4210 non-null   object 
 7   KOD_OKR     4210 non-null   int64  
 8   KRAJ        4210 non-null   object 
 9   LAT         4210 non-null   float64
 10  LNG         4210 non-null   float64
dtypes: float64(2), int64(2), object(7)
memory usage: 361.9+ KB


In [40]:
data.columns

Index(['Unnamed: 0', 'DOBEC', 'OBEC', 'OKRES', 'PSC', 'DPOSTA', 'POSTA',
       'KOD_OKR', 'KRAJ', 'LAT', 'LNG'],
      dtype='object')

## Úloha: Vyfiltruj len niektré stĺpce

In [41]:
valid_cols = ['KRAJ', 'OKRES', 'OBEC', 'LAT', 'LNG']
valid_cols

['KRAJ', 'OKRES', 'OBEC', 'LAT', 'LNG']

In [42]:
data = data[valid_cols]
data.head()

KRAJ            OKRES         OBEC        LAT        LNG
0   BC          Lučenec      Ábelová  48.410817  19.431741
1   BC  Rimavská Sobota       Abovce  48.318828  20.339351
2   TA          Galanta      Abrahám  48.250846  17.616963
3   PV         Bardejov  Abrahámovce  49.161432  21.343484
4   PV         Kežmarok  Abrahámovce  49.044580  20.439083

## Úloha: Nahraď skratky krajov za celé názvy

In [43]:
data.KRAJ.unique()

array(['BC', 'TA', 'PV', 'ZI', 'TC', 'KI', 'NI', 'BL'], dtype=object)

In [44]:
kraj_mask={'BC':'Banskobystricky', 'TA':'Trnavsky', 'PV':'Presovsky', 'ZI':'Zilinsky', 
           'TC':'Trenciansky', 'KI':'Kosicky', 'NI':'Nitriansky', 'BL':'Bratislavsky'}

kraj_mask.__class__

dict

In [45]:
data.replace(kraj_mask, inplace=True)
data.head()

KRAJ            OKRES         OBEC        LAT        LNG
0  Banskobystricky          Lučenec      Ábelová  48.410817  19.431741
1  Banskobystricky  Rimavská Sobota       Abovce  48.318828  20.339351
2         Trnavsky          Galanta      Abrahám  48.250846  17.616963
3        Presovsky         Bardejov  Abrahámovce  49.161432  21.343484
4        Presovsky         Kežmarok  Abrahámovce  49.044580  20.439083

## Interaktívne zobrazenie a vyhľadávanie

In [47]:
from itables import show

In [48]:
show(data, buttons=['copyHtml5','excelHtml5', 'csvHtml5'])

In [49]:
show (data,
      layout={'top1': 'searchPanes'},
      searchPanes = {'layout': 'columns-3', 'cascadePanes': True})

In [50]:
show(
    data,
    layout={'top1':'searchBuilder'},
    searchBuilder={
        'preDefined':{
            'criteria':[
                {'data':'category', 'condition':'=', 'value':['WARRANTS']}
            ]
        }
    }
)

## ..

## Sample z dataframu

### Vytvorenie sample

In [55]:
sample = data.sample(40)
sample.head()

KRAJ              OKRES               OBEC        LAT        LNG
1421      Kosicky           Trebišov             Kinčeš  48.730260  21.701220
406      Zilinsky              Čadca            Čadečka  49.454363  18.785356
3020  Trenciansky          Prievidza  Rudnianska Lehota  48.805783  18.463193
812   Trenciansky             Púchov           Gaškovce  49.123565  18.324120
2770    Presovsky  Vranov nad Topľou               Poša  48.838746  21.754259

### Resetovanie indexu

In [57]:
sample.reset_index(inplace=True)
sample.head()

index         KRAJ              OKRES               OBEC        LAT  \
0   1421      Kosicky           Trebišov             Kinčeš  48.730260   
1    406     Zilinsky              Čadca            Čadečka  49.454363   
2   3020  Trenciansky          Prievidza  Rudnianska Lehota  48.805783   
3    812  Trenciansky             Púchov           Gaškovce  49.123565   
4   2770    Presovsky  Vranov nad Topľou               Poša  48.838746   

         LNG  
0  21.701220  
1  18.785356  
2  18.463193  
3  18.324120  
4  21.754259

In [58]:
sample.drop(columns='index', inplace=True)
sample.head()

KRAJ              OKRES               OBEC        LAT        LNG
0      Kosicky           Trebišov             Kinčeš  48.730260  21.701220
1     Zilinsky              Čadca            Čadečka  49.454363  18.785356
2  Trenciansky          Prievidza  Rudnianska Lehota  48.805783  18.463193
3  Trenciansky             Púchov           Gaškovce  49.123565  18.324120
4    Presovsky  Vranov nad Topľou               Poša  48.838746  21.754259

### "Stred" Slovenska na mape

In [64]:
data[data.OBEC == 'Zvolen']

KRAJ   OKRES    OBEC        LAT        LNG
4154  Banskobystricky  Zvolen  Zvolen  48.576181  19.137116

In [65]:
data[data.OBEC == 'Zvolen'][['LAT', 'LNG']]

LAT        LNG
4154  48.576181  19.137116

In [68]:
data[data.OBEC == 'Púchov'][['LAT', 'LNG']].values

array([[49.1235654, 18.3241203]])

In [66]:
data[data.OBEC == 'Púchov'][['LAT', 'LNG']].values[0]

array([49.1235654, 18.3241203])

In [73]:
stred = data[data.OBEC == 'Púchov'][['LAT', 'LNG']].values[0]
stred

array([49.1235654, 18.3241203])

### Mapa - folium

pip install folium

In [75]:
import folium

In [85]:
sample.head()

KRAJ              OKRES               OBEC        LAT        LNG
0      Kosicky           Trebišov             Kinčeš  48.730260  21.701220
1     Zilinsky              Čadca            Čadečka  49.454363  18.785356
2  Trenciansky          Prievidza  Rudnianska Lehota  48.805783  18.463193
3  Trenciansky             Púchov           Gaškovce  49.123565  18.324120
4    Presovsky  Vranov nad Topľou               Poša  48.838746  21.754259

In [84]:
mapa = folium.Map(location=stred, width=600, height=250, zoom_start=6)
for _,row in sam
mapa